dist: bionic

language: go

env: GO111MODULE=on

go:
  - 1.13.x

sudo: required

services:
  - docker

os:
  - linux

branches:
  only:
    - master
    - stable

before_install:
  - chmod +x build.sh
  - git clone https://github.com/shaohung001/ginFastApp.git ../ginFastApp
  - ls ../
  - ls .
  - npm -v
  - echo "DOCEKR_USER:$DOCKER_USER"

install: true

notifications:
  email: false

script:
  - ./build.sh