dist: bionic

language: go

env: GO111MODULE=on

go:
  - 1.13.x

sudo: required

os:
  - linux
  - osx

before_install:
  - echo "\n\nmachine github.com\n"
  - git clone https://github.com/shaohung001/ginFastApp

git:
  depth: 1

install: true

notifications:
  email: false

script:
  - .travis/build.sh