dist: bionic

language: go

env: GO111MODULE=on

go:
  - 1.13.x

sudo: required

os:
  - osx

before_install:
  - chmod +x build.sh
  - git clone https://github.com/shaohung001/ginFastApp.git ../ginFastApp
  - ls ../
  - ls .
  - npm -v

install: true

notifications:
  email: false

script:
  - ./build.sh