dist: bionic

language: go

env: GO111MODULE=on

go:
  - 1.13.x

sudo: required

os:
  - osx

before_install:
  - chmod +x build.sh
  - git clone git@github.com:shaohung001/ginFastApp.git ../ginFastApp

install: true

notifications:
  email: false

script:
  - .travis/build.sh