dist: bionic

language: go

env: GO111MODULE=on

go:
  - 1.13.x

sudo: required

os:
  - linux
  - osx

before_install:
  - go get github.com/shaohung001/ginFastApp

install: true

notifications:
  email: false

script:
  - .travis/build.sh